# Site settings
title: Manish Gill
email: contact@manishgill.com
description: "Personal website of Manish Gill"
baseurl: ""
url: "http://manishgill.com"
twitter_username: mgill25 
github_username: mgill25 

# Build settings
markdown: kramdown
permalink: pretty
sass:
  sass_dir: /css/imports/
